# This file defines the CI for the BSDF repo.

# todo: py34, pypy3

job_py27:
  image: python:2.7
  script:
    - cd bsdf
    - cd
    - python --version
    - pip install invoke
    - invoke py.test_unit


job_py36:
  image: python:3.6
  script:
    - cd bsdf
    - cd
    - python --version
    - pip install invoke
    - invoke py.test_style
    - invoke py.test_unit
    - invoke py.test_shared
