# This file defines the CI for the BSDF repo.

# ---------- Python lite

job_python_lite_py34:
  image: python:3.4
  script:
    - cd py_lite
    - pip install invoke flake8 pytest pytest-cov
    #
    - python --version
    - invoke -l
    #
    - invoke test-style
    - invoke test-unit
    - invoke test-shared


# ---------- Python

job_python_py27:
  image: python:2.7
  script:
    - cd python
    - pip install invoke pytest pytest-cov
    #
    - python --version
    - invoke -l
    #
    - invoke test-unit
    #- invoke test-shared  this has issues with bytes/unicode/json


job_python_pypy3:
  image: pypy:3
  script:
    - cd python
    - pip install invoke pytest pytest-cov
    #
    - python --version
    - invoke -l
    #
    - invoke test-unit
    - invoke test-shared


job_python_py34:
  image: python:3.4
  script:
    - cd python
    - pip install invoke pytest pytest-cov
    #
    - python --version
    - invoke -l
    #
    - invoke test-unit
    - invoke test-shared


job_python_py36:
  image: python:3.6
  script:
    - cd python
    - pip install invoke flake8 pytest pytest-cov
    #
    - python --version
    - invoke -l
    #
    - invoke test-style
    - invoke test-unit
    - invoke test-shared

# ---------- Octave / Matlab

job_matlab_octave:
  image: almarklein/octave
  script:
    - cd matlab
    - pip install invoke
    #
    - python --version
    - octave-cli --version
    - invoke -l
    #
    - invoke test-unit --octave
    - invoke test-shared --octave


# ---------- Node / JavaScript

# todo: job_js


# ---------- Website

job_pages:
  stage: deploy
  image: python:3.6
  script:
    - pip install invoke markdown
    #
    - python --version
    - invoke -l
    #
    - invoke py.update-readme
    - invoke py_lite.update-readme
    - invoke build-pages
    - mv _pages public  # the name of the artifact matters
  artifacts:
    paths:
      - public
  only:
    - master
    - website
