# This file defines the CI for the BSDF repo.


# ---------- Python

# todo: job_py27:


job_pypy:
  image: pypy:3
  script:
    - cd py
    - pip install invoke pytest pytest-cov
    #
    - python --version
    - invoke -l
    #
    - invoke test-unit
    - invoke test-shared


job_py34:
  image: python:3.4
  script:
    - cd py
    - pip install invoke pytest pytest-cov
    #
    - python --version
    - invoke -l
    #
    - invoke test-unit
    - invoke test-shared


job_py36:
  image: python:3.6
  script:
    - cd py
    - pip install invoke flake8 pytest pytest-cov
    #
    - python --version
    - invoke -l
    #
    - invoke test-style
    - invoke test-unit
    - invoke test-shared

# ---------- Octave / Matlab

job_octave:
  image: almarklein/octave
  script:
    - cd matlab
    - pip install invoke
    #
    - python --version
    - octave-cli --version
    - invoke -l
    #
    - invoke test-unit --octave
    - invoke test-shared --octave


# ---------- Node / JavaScript

# todo: job_js

